(()=>{
const V2_TABS=['Summary','Distribution','Targets & Risk','Drivers','Correlations','Convergence','Failures','Stress Tests','Compare','Reproducibility'];
G._simulationApi=async function(path,options={}){return this._automationApi(path,{...options,query:options.query||''})};
G.ensureSimulationV2UI=function(){
 const aside=document.querySelector('#simulateModal .sim-builder-grid aside .sim-panel-body');if(!aside||document.getElementById('simSamplingMethod'))return;
 const correlation=[...aside.querySelectorAll('details')].find(x=>x.textContent.includes('Correlation'));
 const block=document.createElement('div');block.id='simV2Settings';block.innerHTML=`
 <details class="sim-v2-section" open><summary>3. Sampling method</summary><div class="sim-v2-fields"><label class="sim-field"><span>Method</span><select id="simSamplingMethod" class="cfg-inp" onchange="document.getElementById('simHistoricalJoint').style.display=this.value==='historical_joint'?'':'none'"><option value="pseudorandom">Standard random</option><option value="latin_hypercube">Latin Hypercube</option><option value="antithetic">Antithetic</option><option value="quasi_random">Quasi-random (Halton)</option><option value="historical_joint">Historical joint resampling</option></select></label><label id="simHistoricalJoint" class="sim-field" style="display:none"><span>Historical joint rows (JSON arrays or inputId objects)</span><textarea id="simHistoricalJointRows" class="cfg-inp" rows="3" placeholder='[[10,20],[12,18]]'></textarea></label><p>Method and seed are stored with every reproducible result.</p></div></details>
 <details class="sim-v2-section"><summary>4. Convergence and stopping</summary><div class="sim-v2-fields"><label><input id="simConvergenceEnabled" type="checkbox" checked> Calculate convergence diagnostics</label><label><input id="simEarlyStopping" type="checkbox"> Stop early after every output is stable at three checkpoints</label><label class="sim-field"><span>Minimum trials</span><input id="simMinTrials" class="cfg-inp" type="number" min="500" value="1000"></label><label class="sim-field"><span>Relative MCSE tolerance</span><input id="simMcseTolerance" class="cfg-inp" type="number" min="0.0001" max="0.5" step="0.001" value="0.01"></label></div></details>
 <details class="sim-v2-section"><summary>5. Targets and risk</summary><div class="sim-v2-fields"><p>Set a target and direction on each output. Results include target probabilities, VaR/CVaR, downside deviation, MCSE, and valid-trial rate.</p></div></details>
 <details class="sim-v2-section"><summary>6. Stress and reverse stress</summary><div class="sim-v2-fields"><label class="sim-field"><span>Changes (one inputId=value per line)</span><textarea id="simStressChanges" class="cfg-inp" rows="2" placeholder="input-1=80"></textarea></label><div><button type="button" class="rb" onclick="G.previewSimulationStress()">Preview stress</button> <button type="button" class="rb" onclick="G.previewReverseStress()">Reverse stress</button></div></div></details>
 <details class="sim-v2-section"><summary>7. Report and retention</summary><div class="sim-v2-fields"><label><input id="simRawTrials" type="checkbox"> Retain raw trials (maximum 10,000)</label><p>Summary results use bounded storage. Raw trials remain opt-in and follow the workspace retention policy.</p></div></details>`;
 aside.insertBefore(block,correlation||document.getElementById('simStatus'));if(correlation){correlation.querySelector('summary').textContent='8. Correlation model';correlation.querySelector('div').insertAdjacentHTML('afterbegin','<label class="sim-field"><span>Correlation target</span><select id="simCorrelationMethod" class="cfg-inp"><option value="pearson">Pearson</option><option value="spearman">Spearman rank</option></select></label><label style="display:block;margin:7px 0"><input id="simRepairCorrelation" type="checkbox"> Preview and explicitly repair a non-PSD matrix</label>')}
 const status=document.getElementById('simStatus');if(status)status.insertAdjacentHTML('beforebegin','<div class="cfg-label" style="margin-top:11px">9. Validate and run</div>');
 };
G.ensureSimulationV2Rows=function(){document.querySelectorAll('#simInputs .sim-row').forEach(row=>{if(row.querySelector('.sim-bound-mode'))return;const dist=row.querySelector('.sim-dist'),field=document.createElement('label');field.className='sim-field sim-bound-field';field.innerHTML='<span>Bounds</span><select class="cfg-inp sim-bound-mode" title="Truncate samples correctly, clip at bounds, reject out-of-range draws, or ignore bounds"><option value="truncate">True truncation</option><option value="clip">Clip</option><option value="reject">Reject and redraw</option><option value="none">No bounds</option></select>';const advanced=row.querySelector('.sim-advanced');(advanced||dist?.parentElement||row).appendChild(field);const kind=dist?.value;field.querySelector('select').value=['normal','lognormal'].includes(kind)?'truncate':'none'})};
G.openSimulate=function(){const modal=document.getElementById('simulateModal');if(!modal){this.toast('Alaada Simulate could not be loaded. Refresh the page and try again.','err');return false}modal.style.display='flex';try{if(!document.querySelector('#simInputs .sim-row'))this.addSimInput({sheet:this.sh.name,cell:this.ref(this.row,this.col)});if(!document.querySelector('#simOutputs .sim-row'))this.addSimOutput({sheet:this.sh.name,cell:this.ref(this.row,this.col)});this.ensureSimulationV2UI();this.ensureSimulationV2Rows();this.updateSimulationEstimate();this.refreshSimulationCorrelations();this._simulationStatus('Ready. Your live workbook is never changed during a run.')}catch(error){this._simulationStatus(`Setup needs attention: ${error.message||'Could not initialize Simulation 2.0.'}`,'error');this.toast('Simulate opened with a setup warning','warn')}setTimeout(()=>modal.querySelector('input')?.focus(),30);return true};
const priorAddInput=G.addSimInput.bind(G);G.addSimInput=function(item={}){const result=priorAddInput(item);this.ensureSimulationV2Rows();const row=document.querySelector('#simInputs .sim-row:last-child'),select=row?.querySelector('.sim-bound-mode');if(select)select.value=item.distribution?.boundMode||item.distribution?.bound_mode||(['normal','lognormal'].includes(item.distribution?.type)?'truncate':'none');return result};
const priorPayload=G._simulationPayload.bind(G);G._simulationPayload=function(){const payload=priorPayload();payload.config.schemaVersion=2;payload.config.samplingMethod=document.getElementById('simSamplingMethod')?.value||'pseudorandom';payload.config.correlationMethod=payload.config.correlations.length?(document.getElementById('simCorrelationMethod')?.value||'pearson'):'none';payload.config.repairCorrelationMatrix=!!document.getElementById('simRepairCorrelation')?.checked;payload.config.convergence={enabled:!!document.getElementById('simConvergenceEnabled')?.checked,earlyStopping:!!document.getElementById('simEarlyStopping')?.checked,minimumTrials:Number(document.getElementById('simMinTrials')?.value)||1000,requiredStableCheckpoints:3,checkEvery:500,relativeMcseTolerance:Number(document.getElementById('simMcseTolerance')?.value)||.01};payload.config.storeRawTrials=!!document.getElementById('simRawTrials')?.checked;if(payload.config.samplingMethod==='historical_joint'){try{payload.config.historicalJointSamples=JSON.parse(document.getElementById('simHistoricalJointRows')?.value||'[]')}catch{throw new Error('Historical joint rows must be valid JSON.')}}document.querySelectorAll('#simInputs .sim-row').forEach((row,index)=>payload.config.inputs[index].distribution.boundMode=row.querySelector('.sim-bound-mode')?.value||'none');return payload};
G.runSimulationV2=async function(payload){const request={workspace_id:payload.workspace_id,workbook_id:payload.workbook_id,config:payload.config,sheets:payload.sheets,idempotency_key:`browser:${payload.workbook_id}:${Date.now()}`},validation=await this._simulationApi('/simulations/validate',{method:'POST',body:{config:payload.config,sheets:payload.sheets}});if(!validation.valid)throw new Error((validation.errors||[]).join(' · '));this._simulationStatus((validation.warnings||[]).join(' · ')||'Validated · starting Simulation 2.0…');const data=await this._simulationApi('/simulations/run',{method:'POST',body:request}),run=data.run;this._simulationState.jobId=run.id;this._simulationState.payload=payload;if(run.result_summary)this.showSimulationResults(run.result_summary);else this.pollSimulationV2(run.id);return data};
G.pollSimulationV2=function(runId){clearInterval(this._simulationState.poll);this._simulationState.poll=setInterval(async()=>{try{const data=await this._simulationApi(`/simulations/runs/${encodeURIComponent(runId)}/progress`),run=data.run,percent=Math.round(Number(run.progress||0)*100);document.getElementById('simProgressBar').style.width=`${percent}%`;this._simulationStatus(`${run.status} · ${Number(run.trials_completed||0).toLocaleString()} of ${Number(run.trials_requested||0).toLocaleString()} trials · ${percent}%`);if(['completed','cancelled','failed'].includes(run.status)){clearInterval(this._simulationState.poll);document.getElementById('simRunBtn').disabled=false;document.getElementById('simCancelBtn').style.display='none';const failure=run.result_summary?.error;if(run.status==='failed'&&failure){const error=new Error(failure.message);error.code=failure.code;error.detail=failure;this._simulationHandleError(error)}else if(run.result_summary)this.showSimulationResults(run.result_summary);else this._simulationStatus('The run ended without a result summary.','error')}}catch(error){clearInterval(this._simulationState.poll);this._simulationHandleError(error)}},1200)};
const legacyRun=G.runSimulation.bind(G);G.runSimulation=async function(){let payload;try{payload=this._simulationPayload()}catch(error){return this._simulationStatus(error.message,'error')}if(payload.config.repairCorrelationMatrix&&!await this.confirmAutomationAction('Preview and apply the nearest safe positive-semidefinite correlation repair for this run? The configured targets will be reported with the repaired matrix.'))return;if(!payload.workspace_id||!navigator.onLine)return legacyRun();const button=document.getElementById('simRunBtn'),cancel=document.getElementById('simCancelBtn');button.disabled=true;cancel.style.display='';document.getElementById('simProgressBar').style.width='2%';try{return await this.runSimulationV2(payload)}catch(error){button.disabled=false;cancel.style.display='none';this._simulationHandleError(error)}};
const legacyCancel=G.cancelSimulation.bind(G);G.cancelSimulation=async function(){if(!this._simulationState.payload?.workspace_id)return legacyCancel();try{await this._simulationApi(`/simulations/runs/${encodeURIComponent(this._simulationState.jobId)}/cancel`,{method:'POST'});this._simulationStatus('Cancellation requested · the worker will stop safely after the current trial.')}catch(error){this._simulationStatus(error.message,'error')}};
G.openSimulationResults=function(){this.openSimulate();if(!this._simulationState.result)this.toast('Run or load a simulation to view results','inf');else{document.getElementById('simResults').scrollIntoView({behavior:'smooth',block:'start'});this.renderSimulationV2Tab('Summary')}};
G._simV2Number=function(value){return Number.isFinite(Number(value))?Number(value).toLocaleString(undefined,{maximumFractionDigits:5}):'—'};
G.renderSimulationV2Tab=function(name){const result=this._simulationState.result;if(!result)return;document.querySelectorAll('.sim-v2-tabs button').forEach(button=>button.classList.toggle('active',button.dataset.tab===name));const target=document.getElementById('simV2ResultBody'),esc=x=>this.esc(String(x??'')),num=x=>this._simV2Number(x),outputs=result.outputs||[],cards=items=>`<div class="sim-v2-grid">${items.join('')}</div>`;let html='';
 if(name==='Summary')html=cards([`<div class="sim-v2-card">Trials<b>${Number(result.trialsCompleted||0).toLocaleString()}</b></div>`,`<div class="sim-v2-card">Sampling<b>${esc(result.samplingMethod||'pseudorandom')}</b></div>`,`<div class="sim-v2-card">Valid trials<b>${num(result.effectiveValidTrialPercentage)}%</b></div>`,`<div class="sim-v2-card">Convergence<b>${esc(result.convergenceStatus||'not checked')}</b></div>`,...outputs.map(o=>`<div class="sim-v2-card">${esc(o.name)}<b>${num(o.mean)}</b><small>P05–P95 ${num(o.percentiles?.p05)} – ${num(o.percentiles?.p95)}</small></div>`)]);
 else if(name==='Distribution')html=outputs.map(o=>`<div class="sim-v2-card"><b>${esc(o.name)}</b><p>Min ${num(o.minimum)} · Median ${num(o.median)} · Max ${num(o.maximum)}</p><p>Mean ${num(o.mean)} · Std dev ${num(o.standardDeviation)} · Skew ${num(o.skewness)}</p></div>`).join('');
 else if(name==='Targets & Risk')html=`<table class="help-table"><thead><tr><th>Output</th><th>Below target</th><th>Above target</th><th>VaR 95</th><th>CVaR 95</th><th>Downside deviation</th></tr></thead><tbody>${outputs.map(o=>`<tr><td>${esc(o.name)}</td><td>${num(o.probabilityBelowTarget)}</td><td>${num(o.probabilityAboveTarget)}</td><td>${num(o.valueAtRisk95)}</td><td>${num(o.conditionalValueAtRisk95)}</td><td>${num(o.downsideDeviation)}</td></tr>`).join('')}</tbody></table>`;
 else if(name==='Drivers')html=outputs.map(o=>`<div class="sim-v2-card"><b>${esc(o.name)}</b>${(o.sensitivity||[]).map(s=>`<p>${esc(s.input)} · ${(Number(s.influenceScore||0)*100).toFixed(1)}% · ${esc(s.direction)}</p>`).join('')||'<p>No measurable drivers.</p>'}</div>`).join('');
 else if(name==='Correlations')html=`<table class="help-table"><thead><tr><th>Inputs</th><th>Pearson</th><th>Spearman</th></tr></thead><tbody>${(result.realisedCorrelations||[]).map(c=>`<tr><td>${esc(c.inputA)} ↔ ${esc(c.inputB)}</td><td>${num(c.pearson??c.correlation)}</td><td>${num(c.spearman)}</td></tr>`).join('')}</tbody></table>`;
 else if(name==='Convergence')html=`<p>${esc(result.convergenceStatus||'not checked')}</p><table class="help-table"><thead><tr><th>Trial</th><th>Mean</th><th>MCSE</th><th>Relative MCSE</th></tr></thead><tbody>${(result.convergencePoints||[]).flatMap(p=>(p.outputs||[]).map(o=>`<tr><td>${p.trial}</td><td>${num(o.mean)}</td><td>${num(o.monteCarloStandardError)}</td><td>${num(o.relativeMcse)}</td></tr>`)).join('')}</tbody></table>`;
 else if(name==='Failures')html=cards([`<div class="sim-v2-card">Valid trials<b>${num(result.effectiveValidTrialPercentage)}%</b></div>`,...Object.entries(result.failedTrialCategories||{}).map(([key,value])=>`<div class="sim-v2-card">${esc(key)}<b>${value}</b></div>`),...(result.warnings||[]).map(w=>`<div class="sim-v2-warning">${esc(w)}</div>`)]);
 else if(name==='Stress Tests')html='<div class="sim-v2-card"><b>Deterministic and reverse stress</b><p>Enter fixed input changes in Setup, preview the recalculated outputs, then use Goal Seek or Solver for a constrained reverse-stress solution. Workbook cells are never changed by a preview.</p><button onclick="G.previewSimulationStress()">Preview configured stress</button></div>';
 else if(name==='Compare')html='<div class="sim-v2-card"><b>Run comparison</b><p>Compare the latest two reproducible runs by output statistics, risk, sampling method, seed, and configuration hash.</p><button onclick="G.compareSimulationRuns()">Compare latest runs</button></div>';
 else html=cards([`<div class="sim-v2-card">Engine<b>${esc(result.engineVersion||'1.x migrated')}</b></div>`,`<div class="sim-v2-card">Seed<b>${esc(result.seed)}</b></div>`,`<div class="sim-v2-card">Config hash<b style="font-size:9px;word-break:break-all">${esc(result.configurationHash)}</b></div>`,`<div class="sim-v2-card">Sampling<b>${esc(result.samplingMethod)}</b></div>`]);target.innerHTML=html||'<div class="sim-v2-card">No data for this tab.</div>'};
const priorResults=G.showSimulationResults.bind(G);G.showSimulationResults=function(result){const value=priorResults(result);const root=document.getElementById('simResults');root.querySelectorAll(':scope>section.sim-panel').forEach(section=>section.style.display='none');let shell=document.getElementById('simV2Results');if(!shell){shell=document.createElement('section');shell.id='simV2Results';shell.innerHTML=`<nav class="sim-v2-tabs" aria-label="Simulation result views">${V2_TABS.map(name=>`<button data-tab="${name}" onclick="G.renderSimulationV2Tab('${name.replace(/'/g,"\\'")}')">${name}</button>`).join('')}</nav><div id="simV2ResultBody" class="sim-v2-result"></div>`;root.prepend(shell)}this.renderSimulationV2Tab('Summary');return value};
G._parseStressChanges=function(){const changes={};for(const line of String(document.getElementById('simStressChanges')?.value||'').split(/\r?\n/)){if(!line.trim())continue;const [key,value]=line.split('=');if(!key?.trim()||!Number.isFinite(Number(value)))throw new Error(`Invalid stress line: ${line}`);changes[key.trim()]=Number(value)}if(!Object.keys(changes).length)throw new Error('Enter at least one inputId=value stress change.');return changes};
G.previewSimulationStress=async function(){try{const payload=this._simulationPayload(),changes=this._parseStressChanges();if(payload.workspace_id){const data=await this._simulationApi('/simulations/stress-tests/run',{method:'POST',body:{config:payload.config,sheets:payload.sheets,changes}});this.toast(`Stress preview ready: ${JSON.stringify(data.result).slice(0,180)}`,'ok')}else this.toast(`Stress preview configured for ${Object.keys(changes).length} inputs. Connect the workbook to calculate it server-side.`,'inf')}catch(error){this.toast(error.message,'warn')}};
G.previewReverseStress=function(){try{this._parseStressChanges();this.toast('Reverse stress uses What-If Goal Seek/Solver preview and requires Apply before changing cells.','inf')}catch(error){this.toast(error.message,'warn')}};
const priorCommands=G._commands.bind(G);G._commands=function(){return[...priorCommands(),{label:'Open Alaada Simulate 2.0',category:'Data',keywords:'monte carlo lhs antithetic quasi random risk stress',action:()=>this.openSimulate()},{label:'Open Simulation Results',category:'Analyze',keywords:'convergence mcse var cvar sensitivity probability',action:()=>this.openSimulationResults()}]};
})();
